import type { ConfiguratorLabels, Locale } from "./types";

const de: ConfiguratorLabels = {
  title: "G-Force Konfigurator",
  titleWord: "Konfigurator",
  message: "Werkstatt",
  badge: "3D · G-Force®",
  hint: "Parts Library · Geräteansicht · Partlist",
  backLabel: "Zur Website",
  libraryTitle: "Parts Library",
  allCategories: "Alle",
  searchPlaceholder: "Suche Teilenummer, Name…",
  detailTitle: "Detail",
  partNumber: "Teilenummer",
  categoryLabel: "Kategorie",
  stageLabel: "Arbeitsbereich",
  selectHint: "Wählen Sie ein Gerät aus der Parts Library.",
  addToTray: "Zur Partlist hinzufügen",
  removeFromTray: "Entfernen",
  trayLabel: "Partlist",
  clearTray: "Leeren",
  requestLabel: "Anfrage senden",
  emptyLibrary: "Keine Geräte gefunden.",
  noImage: "Bild folgt",
  partlistTitle: "Partlist",
  emptyPartlist: "Keine Teile – Gerät wählen.",
  deletePart: "Teil entfernen",
  selectedPart: "Ausgewählt",
  viewImage: "Bild",
  hintRotate: "Drehen",
  hintZoom: "Zoom",
  hintDrag: "Teil ziehen",
  resetView: "Reset",
  hintSelect: "Im 3D-Modell anklicken und mit den Pfeilen verschieben.",
  lengthLabel: "Länge",
};

const en: ConfiguratorLabels = {
  title: "G-Force Configurator",
  titleWord: "Configurator",
  message: "Workshop",
  badge: "3D · G-Force®",
  hint: "Parts Library · Unit view · Partlist",
  backLabel: "Back to website",
  libraryTitle: "Parts Library",
  allCategories: "All",
  searchPlaceholder: "Search part number, name…",
  detailTitle: "Detail",
  partNumber: "Part number",
  categoryLabel: "Category",
  stageLabel: "Workspace",
  selectHint: "Select a unit from the Parts Library.",
  addToTray: "Add to partlist",
  removeFromTray: "Remove",
  trayLabel: "Partlist",
  clearTray: "Clear",
  requestLabel: "Send request",
  emptyLibrary: "No units found.",
  noImage: "Image soon",
  partlistTitle: "Partlist",
  emptyPartlist: "No parts – select a unit.",
  deletePart: "Remove part",
  selectedPart: "Selected",
  viewImage: "Image",
  hintRotate: "Rotate",
  hintZoom: "Zoom",
  hintDrag: "Drag part",
  resetView: "Reset",
  hintSelect: "Click the part in 3D and drag with the handles.",
  lengthLabel: "Length",
};

const zh: ConfiguratorLabels = {
  title: "G-Force 配置器",
  titleWord: "配置器",
  message: "车间",
  badge: "3D · G-Force®",
  hint: "零件库 · 设备视图 · 零件列表",
  backLabel: "返回网站",
  libraryTitle: "零件库",
  allCategories: "全部",
  searchPlaceholder: "搜索零件号、名称…",
  detailTitle: "详情",
  partNumber: "零件号",
  categoryLabel: "类别",
  stageLabel: "工作区",
  selectHint: "请从零件库选择设备。",
  addToTray: "加入零件列表",
  removeFromTray: "移除",
  trayLabel: "零件列表",
  clearTray: "清空",
  requestLabel: "发送申请",
  emptyLibrary: "未找到设备。",
  noImage: "图片待补充",
  partlistTitle: "零件列表",
  emptyPartlist: "无零件——请选择设备。",
  deletePart: "删除零件",
  selectedPart: "已选",
  viewImage: "图片",
  hintRotate: "旋转",
  hintZoom: "缩放",
  hintDrag: "拖动零件",
  resetView: "重置",
  hintSelect: "在 3D 中点击零件并用手柄拖动。",
  lengthLabel: "长度",
};

export const configuratorLabels: Record<Locale, ConfiguratorLabels> = {
  de,
  en,
  zh,
};
